alias conf-vim="nvim ~/.config/nvim/init.vim"
alias conf-alacritty="nvim ~/.config/alacritty/alacritty.yml"
alias conf-zsh="nvim ~/.zshrc ~/.zshrc.d/*"
alias conf-tmux="nvim ~/.tmux.conf"
alias conf-starship="nvim ~/.config/starship.toml"
