add_newline = false

format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
${custom.shlvl}\
$character
"""

[directory]
style = "blue"

[custom.shlvl]
command = "printf '❯%.0s' {1..$(($SHLVL-2))}"
when = "[[ $SHLVL -ge 3 ]]"
format = "[$output](bold yellow)"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[git_branch]
symbol = " "
format = "[on](white) [$symbol$branch](purple) "

[git_commit]
style = "green"

[git_status]
format = '$all_status$ahead_behind'
conflicted = '[=$count](red) '
ahead = '[⇡$count](green) '
behind = '[⇣$count](yellow) '
diverged = '[⇕$count](red) '
untracked = '[?$count](red) '
stashed = '[\$$count](yellow) '
modified = '[!$count](yellow) '
staged = '[+$count](green) '
renamed = '[»$count](green) '
deleted = '[✘$count](red) '
