# docs: https://pimsync.whynothugo.nl/
# vim: ft=cfg

status_path "~/.local/share/pimsync/status/"

# ╔════════════════════════════════════════════════════════════════════════════╗
# ║ Calendar                                                                   ║
# ╚════════════════════════════════════════════════════════════════════════════╝

pair calendars {
  storage_a calendars_local
  storage_b calendars_remote
  collections from b
  on_empty sync
  conflict_resolution cmd nvim -d
}

storage calendars_local {
  type vdir/icalendar
  path ~/.local/share/calendars/
}

storage calendars_remote {
  type caldav
  url {
    cmd gopass show -o cdav/url
  }
  username {
    cmd gopass show -o cdav/username
  }
  password {
    cmd gopass show -o cdav/password
  }
}

# ╔════════════════════════════════════════════════════════════════════════════╗
# ║ Holidays                                                                   ║
# ╚════════════════════════════════════════════════════════════════════════════╝

pair holidays {
  storage_a calendars_local
  storage_b holidays_remote
  collection holidays
}

storage holidays_remote {
  type webcal
  collection_id holidays
  url https://www.thunderbird.net/media/caldata/autogen/PeruHolidays.ics
}

# ╔════════════════════════════════════════════════════════════════════════════╗
# ║ Contacts                                                                   ║
# ╚════════════════════════════════════════════════════════════════════════════╝

pair contacts {
  storage_a contacts_local
  storage_b contacts_remote
  collections all
  conflict_resolution cmd nvim -d
}

storage contacts_local {
  type vdir/vcard
  path ~/.local/share/contacts/
}

storage contacts_remote {
  type carddav
  url {
    cmd gopass show -o cdav/url
  }
  username {
    cmd gopass show -o cdav/username
  }
  password {
    cmd gopass show -o cdav/password
  }
}
