# docs: http://www.musicpd.org/doc/user/

music_directory     "~/music"
playlist_directory  "$XDG_CONFIG_HOME/mpd/playlists"
db_file             "$XDG_CACHE_HOME/mpd/database"

audio_output {
  type  "pulse"
  name  "PulseAudio"
}
