# https://github.com/doronbehar/pistol

fpath .*.env$ sh: echo %pistol-filename% '[REDACTED]'
fpath .*.key$ sh: echo %pistol-filename% '[REDACTED]'
fpath .*.pem$ sh: echo %pistol-filename% '[REDACTED]'

application/epub\+zip    sh: ebook-meta %pistol-filename%
application/json         sh: jq -C '.' %pistol-filename%
application/pdf          sh: pdfinfo %pistol-filename%
application/vnd.sqlite3  sh: sqlite3 %pistol-filename% .schema | pg_format | bat --paging=never --color=always --style=plain --language=sql
application/x-bittorrent sh: transmission-show %pistol-filename%

text/calendar sh: icalendar %pistol-filename%
text/csv      sh: mlr --icsv --opprint cat %pistol-filename% --always-color 
text/*        sh: bat --paging=never --color=always %pistol-filename%
