add_newline = false

format = """
$python\
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$shell\
$character
"""

[line_break]
disabled = false

[directory]
style = "bold #d88736"

[username]
show_always = true
format = "[$user]($style)[@](#d88736)"
style_user = "bold #c2c2c2"

[hostname]
ssh_only = false
format = "[$hostname]($style) "
style = "bold #c2c2c2"

[character]
success_symbol = "[❯](bold #d88736)"
error_symbol = "[❯](bold red)"

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
python_binary = "python3"
disabled = false
