add_newline = false

format = """
$python\
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$battery\
$character
"""

[directory]
style = "bold #ffb86c"

[username]
show_always = true
format = "[$user]($style)[@](#ffb86c)"
style_user = "bold #c2c2c2"

[hostname]
ssh_only = false
format = "[$hostname]($style) "
style = "bold #c2c2c2"

[character]
success_symbol = "[❯](bold #ffb86c)"
error_symbol = "[❯](bold red)"

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
python_binary = "python3"
disabled = false

[git_branch]
style = "bold #6272a4"
format = "[on](bold #c2c2c2) [$symbol$branch]($style) "

[git_status]
style = "bold #6272a4"

[[battery.display]]
threshold = 15
style = "bold #dd9494"

[[battery.display]]
threshold = 30
style = "#f4f49b"
