add_newline = false

format = """
$directory\
$git_branch\
$git_commit\
$git_status\
$nodejs\
$python\
$character
"""

[directory]
style = "blue"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[nodejs]
format = "[via](white) [$symbol($version )]($style)"

[python]
symbol = " "
format = '[via](white) [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
python_binary = "python3"

[git_branch]
style = "blue"
format = "[on](white) [$symbol$branch]($style) "

[git_commit]
style = "bold purple"

[git_status]
style = "bold white"
