add_newline = false

format = '$directory$character'
right_format = '$git_state$git_status$git_branch$git_commit'

[directory]
style = 'blue'

[character]
success_symbol = '[❯](green)'
error_symbol = '[❯](red)'

[git_branch]
format = '[$branch(:$remote_branch)](purple)'

[git_commit]
format = '[$hash](green)'

[git_state]
format = '[$state($progress_current/$progress_total)](cyan) [•](bright-black) '

[git_status]
format = '[$all_status$ahead_behind](yellow)[•](bright-black) '
conflicted = '=$count '
ahead = '⇡$count '
behind = '⇣$count '
diverged = '⇕ '
up_to_date = ' '
untracked = '?$count '
stashed = '\$$count '
modified = '!$count '
staged = '+$count '
renamed = '»$count '
deleted = '✘$count '
