add_newline = false

format = """
$python\
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$shell\
$character
"""

[line_break]
disabled = false

[directory]
style = "bold cyan"

[username]
show_always = true
format = "[$user]($style)[@](cyan)"
style_user = "bold bright-blue"

[hostname]
ssh_only = false
format = "[$hostname]($style) "
style = "bold bright-blue"

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
python_binary = "python3"
disabled = false
