use_nerdfont = true
flip_status_indicators = true
notify = true

[theme]
background = "default"
primary = "default"
secondary = "light black"
title = "green"
playing = "light green"
playing_selected = "light green"
playing_bg = "#282727"
highlight = "green"
highlight_bg = "#282727"
error = "white"
error_bg = "red"
statusbar = "green"
statusbar_progress = "light green"
statusbar_bg = "#282727"
cmdline = "default"
cmdline_bg = "default"
search_match = "yellow"
