# ▄▀▄ █   ▄▀▄ ▄▀▀ █▀▄ █ ▀█▀ ▀█▀ ▀▄▀
# █▀█ █▄▄ █▀█ ▀▄▄ █▀▄ █  █   █   █ 

[general]
import = ["~/.config/alacritty/themes/kanagawa_dragon.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 9

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[mouse]
hide_when_typing = true

[window]
startup_mode = "Windowed"

[window.padding]
x = 10
y = 10

[terminal.shell]
args = ["new-session", "-A", "-s", "main"]
program = "/sbin/tmux"
