# ▄▀▄ █   ▄▀▄ ▄▀▀ █▀▄ █ ▀█▀ ▀█▀ ▀▄▀
# █▀█ █▄▄ █▀█ ▀▄▄ █▀▄ █  █   █   █ 

[[colors.indexed_colors]]
color = "#b6927b"   # dragonOrange
index = 16

[[colors.indexed_colors]]
color = "#b98d7b"   # dragonOrange2
index = 17

[colors.bright]
black = '#a6a69c'   # dragonGray
red = '#e46876'     # waveRed
green = '#87a987'   # dragonGreen
yellow = '#e6c384'  # carpYellow
blue = '#7fb4ca'    # springBlue
magenta = '#938aa9' # springViolet1
cyan = '#7aa89f'    # waveAqua2
white = '#c5c9c5'   # dragonWhite

[colors.normal]
black = '#0d0c0c'   # dragonBlack0
red = '#c4746e'     # dragonRed
green = '#8a9a7b'   # dragonGreen2
yellow = '#c4b28a'  # dragonYellow
blue = '#8ba4b0'    # dragonBlue2
magenta = '#a292a3' # dragonPink
cyan = '#8ea4a2'    # dragonAqua
white = '#c8c093'   # oldWhite

[colors.primary]
background = '#181616'  # dragonBlack3
foreground = '#c5c9c5'  # dragonWhite

[colors.selection]
background = '#2d4f67'  # waveBlue2
foreground = '#c8c093'  # oldWhite

[env]
TERM = "xterm-256color"

[font]
size = 9

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[mouse]
hide_when_typing = true

[window]
startup_mode = "Windowed"

[window.padding]
x = 10
y = 10

[shell]
args = ["new-session", "-A", "-s", "main"]
program = "/sbin/tmux"
